### ISSUE TITLE
Issue in code

### ISSUE THREAD

**Issue by MohammadrezaHashemzadeh** [Saptak625/chem-equation-balancers-java#1]
Hello.
I suggest you fix a bug.
When I insert "(NH4)2Cr2O7 = N2 + H2O + Cr2O3" it doesn't work.
I suggest you update this code.

**Comment by Saptak625** [comment]
Issue occurred only in Chemical Balancer V4. Code for this version has been fixed in the latest commit. Thank you for your feedback!
